// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: calc/calc.proto

package calc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int64                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int64                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_calc_calc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calc_calc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_calc_calc_proto_rawDescGZIP(), []int{0}
}

func (x *AddRequest) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *AddRequest) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *AddRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type AddReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int64                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReply) Reset() {
	*x = AddReply{}
	mi := &file_calc_calc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReply) ProtoMessage() {}

func (x *AddReply) ProtoReflect() protoreflect.Message {
	mi := &file_calc_calc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReply.ProtoReflect.Descriptor instead.
func (*AddReply) Descriptor() ([]byte, []int) {
	return file_calc_calc_proto_rawDescGZIP(), []int{1}
}

func (x *AddReply) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

type RangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int64                  `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To            int64                  `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeRequest) Reset() {
	*x = RangeRequest{}
	mi := &file_calc_calc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeRequest) ProtoMessage() {}

func (x *RangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calc_calc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeRequest.ProtoReflect.Descriptor instead.
func (*RangeRequest) Descriptor() ([]byte, []int) {
	return file_calc_calc_proto_rawDescGZIP(), []int{2}
}

func (x *RangeRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *RangeRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

type NumberReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberReply) Reset() {
	*x = NumberReply{}
	mi := &file_calc_calc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberReply) ProtoMessage() {}

func (x *NumberReply) ProtoReflect() protoreflect.Message {
	mi := &file_calc_calc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberReply.ProtoReflect.Descriptor instead.
func (*NumberReply) Descriptor() ([]byte, []int) {
	return file_calc_calc_proto_rawDescGZIP(), []int{3}
}

func (x *NumberReply) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_calc_calc_proto protoreflect.FileDescriptor

const file_calc_calc_proto_rawDesc = "" +
	"\n" +
	"\x0fcalc/calc.proto\x12\x04calc\"B\n" +
	"\n" +
	"AddRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x03R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x03R\x01b\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"\"\n" +
	"\bAddReply\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x03R\x06result\"2\n" +
	"\fRangeRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x03R\x02to\"#\n" +
	"\vNumberReply\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value2\xcc\x01\n" +
	"\n" +
	"Calculator\x12'\n" +
	"\x03Add\x12\x10.calc.AddRequest\x1a\x0e.calc.AddReply\x126\n" +
	"\vListNumbers\x12\x12.calc.RangeRequest\x1a\x11.calc.NumberReply0\x01\x12,\n" +
	"\x03Sum\x12\x10.calc.AddRequest\x1a\x11.calc.NumberReply(\x01\x12/\n" +
	"\aEchoSum\x12\x10.calc.AddRequest\x1a\x0e.calc.AddReply(\x010\x01B\x17Z\x15LearnGo/api/calc;calcb\x06proto3"

var (
	file_calc_calc_proto_rawDescOnce sync.Once
	file_calc_calc_proto_rawDescData []byte
)

func file_calc_calc_proto_rawDescGZIP() []byte {
	file_calc_calc_proto_rawDescOnce.Do(func() {
		file_calc_calc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calc_calc_proto_rawDesc), len(file_calc_calc_proto_rawDesc)))
	})
	return file_calc_calc_proto_rawDescData
}

var file_calc_calc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_calc_calc_proto_goTypes = []any{
	(*AddRequest)(nil),   // 0: calc.AddRequest
	(*AddReply)(nil),     // 1: calc.AddReply
	(*RangeRequest)(nil), // 2: calc.RangeRequest
	(*NumberReply)(nil),  // 3: calc.NumberReply
}
var file_calc_calc_proto_depIdxs = []int32{
	0, // 0: calc.Calculator.Add:input_type -> calc.AddRequest
	2, // 1: calc.Calculator.ListNumbers:input_type -> calc.RangeRequest
	0, // 2: calc.Calculator.Sum:input_type -> calc.AddRequest
	0, // 3: calc.Calculator.EchoSum:input_type -> calc.AddRequest
	1, // 4: calc.Calculator.Add:output_type -> calc.AddReply
	3, // 5: calc.Calculator.ListNumbers:output_type -> calc.NumberReply
	3, // 6: calc.Calculator.Sum:output_type -> calc.NumberReply
	1, // 7: calc.Calculator.EchoSum:output_type -> calc.AddReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calc_calc_proto_init() }
func file_calc_calc_proto_init() {
	if File_calc_calc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calc_calc_proto_rawDesc), len(file_calc_calc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calc_calc_proto_goTypes,
		DependencyIndexes: file_calc_calc_proto_depIdxs,
		MessageInfos:      file_calc_calc_proto_msgTypes,
	}.Build()
	File_calc_calc_proto = out.File
	file_calc_calc_proto_goTypes = nil
	file_calc_calc_proto_depIdxs = nil
}
