// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: calc/calc.proto

package calc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Calculator_Add_FullMethodName         = "/calc.Calculator/Add"
	Calculator_ListNumbers_FullMethodName = "/calc.Calculator/ListNumbers"
	Calculator_Sum_FullMethodName         = "/calc.Calculator/Sum"
	Calculator_EchoSum_FullMethodName     = "/calc.Calculator/EchoSum"
)

// CalculatorClient is the client API for Calculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalculatorClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddReply, error)
	ListNumbers(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NumberReply], error)
	Sum(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AddRequest, NumberReply], error)
	EchoSum(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AddRequest, AddReply], error)
}

type calculatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorClient(cc grpc.ClientConnInterface) CalculatorClient {
	return &calculatorClient{cc}
}

func (c *calculatorClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddReply)
	err := c.cc.Invoke(ctx, Calculator_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorClient) ListNumbers(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NumberReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Calculator_ServiceDesc.Streams[0], Calculator_ListNumbers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RangeRequest, NumberReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Calculator_ListNumbersClient = grpc.ServerStreamingClient[NumberReply]

func (c *calculatorClient) Sum(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AddRequest, NumberReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Calculator_ServiceDesc.Streams[1], Calculator_Sum_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AddRequest, NumberReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Calculator_SumClient = grpc.ClientStreamingClient[AddRequest, NumberReply]

func (c *calculatorClient) EchoSum(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AddRequest, AddReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Calculator_ServiceDesc.Streams[2], Calculator_EchoSum_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AddRequest, AddReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Calculator_EchoSumClient = grpc.BidiStreamingClient[AddRequest, AddReply]

// CalculatorServer is the server API for Calculator service.
// All implementations must embed UnimplementedCalculatorServer
// for forward compatibility.
type CalculatorServer interface {
	Add(context.Context, *AddRequest) (*AddReply, error)
	ListNumbers(*RangeRequest, grpc.ServerStreamingServer[NumberReply]) error
	Sum(grpc.ClientStreamingServer[AddRequest, NumberReply]) error
	EchoSum(grpc.BidiStreamingServer[AddRequest, AddReply]) error
	mustEmbedUnimplementedCalculatorServer()
}

// UnimplementedCalculatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCalculatorServer struct{}

func (UnimplementedCalculatorServer) Add(context.Context, *AddRequest) (*AddReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedCalculatorServer) ListNumbers(*RangeRequest, grpc.ServerStreamingServer[NumberReply]) error {
	return status.Error(codes.Unimplemented, "method ListNumbers not implemented")
}
func (UnimplementedCalculatorServer) Sum(grpc.ClientStreamingServer[AddRequest, NumberReply]) error {
	return status.Error(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedCalculatorServer) EchoSum(grpc.BidiStreamingServer[AddRequest, AddReply]) error {
	return status.Error(codes.Unimplemented, "method EchoSum not implemented")
}
func (UnimplementedCalculatorServer) mustEmbedUnimplementedCalculatorServer() {}
func (UnimplementedCalculatorServer) testEmbeddedByValue()                    {}

// UnsafeCalculatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalculatorServer will
// result in compilation errors.
type UnsafeCalculatorServer interface {
	mustEmbedUnimplementedCalculatorServer()
}

func RegisterCalculatorServer(s grpc.ServiceRegistrar, srv CalculatorServer) {
	// If the following call panics, it indicates UnimplementedCalculatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Calculator_ServiceDesc, srv)
}

func _Calculator_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Calculator_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calculator_ListNumbers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RangeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServer).ListNumbers(m, &grpc.GenericServerStream[RangeRequest, NumberReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Calculator_ListNumbersServer = grpc.ServerStreamingServer[NumberReply]

func _Calculator_Sum_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServer).Sum(&grpc.GenericServerStream[AddRequest, NumberReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Calculator_SumServer = grpc.ClientStreamingServer[AddRequest, NumberReply]

func _Calculator_EchoSum_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServer).EchoSum(&grpc.GenericServerStream[AddRequest, AddReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Calculator_EchoSumServer = grpc.BidiStreamingServer[AddRequest, AddReply]

// Calculator_ServiceDesc is the grpc.ServiceDesc for Calculator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Calculator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calc.Calculator",
	HandlerType: (*CalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Calculator_Add_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListNumbers",
			Handler:       _Calculator_ListNumbers_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Sum",
			Handler:       _Calculator_Sum_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "EchoSum",
			Handler:       _Calculator_EchoSum_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "calc/calc.proto",
}
