// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: demo/hello.proto

// package 是 proto 内部的命名空间，避免不同文件符号冲突；
// 它和 Go 包名无关，真正的 Go 包名看 go_package。

package demo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// proto3 枚举第一个值必须是 0。
type Level int32

const (
	Level_LEVEL_UNSPECIFIED Level = 0
	Level_LEVEL_BASIC       Level = 1
	Level_LEVEL_PREMIUM     Level = 2
)

// Enum value maps for Level.
var (
	Level_name = map[int32]string{
		0: "LEVEL_UNSPECIFIED",
		1: "LEVEL_BASIC",
		2: "LEVEL_PREMIUM",
	}
	Level_value = map[string]int32{
		"LEVEL_UNSPECIFIED": 0,
		"LEVEL_BASIC":       1,
		"LEVEL_PREMIUM":     2,
	}
)

func (x Level) Enum() *Level {
	p := new(Level)
	*p = x
	return p
}

func (x Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Level) Descriptor() protoreflect.EnumDescriptor {
	return file_demo_hello_proto_enumTypes[0].Descriptor()
}

func (Level) Type() protoreflect.EnumType {
	return &file_demo_hello_proto_enumTypes[0]
}

func (x Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Level.Descriptor instead.
func (Level) EnumDescriptor() ([]byte, []int) {
	return file_demo_hello_proto_rawDescGZIP(), []int{0}
}

// message 是数据结构，字段后的 = 1、= 2 是字段编号（协议里的稳定标识）。
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                     // string
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`                      // int32
	IsVip         bool                   `protobuf:"varint,3,opt,name=is_vip,json=isVip,proto3" json:"is_vip,omitempty"`     // bool，snake_case 会生成 Go 的 IsVip
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`                     // repeated -> Go []string
	Level         Level                  `protobuf:"varint,5,opt,name=level,proto3,enum=hello.Level" json:"level,omitempty"` // 枚举字段
	Address       *Address               `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`               // 另一个 message 作为字段类型 -> Go *Address
	Count         int32                  `protobuf:"varint,7,opt,name=count,proto3" json:"count,omitempty"`                  // 控制 server-streaming 返回条数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_demo_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_demo_hello_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *HelloRequest) GetIsVip() bool {
	if x != nil {
		return x.IsVip
	}
	return false
}

func (x *HelloRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *HelloRequest) GetLevel() Level {
	if x != nil {
		return x.Level
	}
	return Level_LEVEL_UNSPECIFIED
}

func (x *HelloRequest) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *HelloRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Street        string                 `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_demo_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_demo_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_demo_hello_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_demo_hello_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_demo_hello_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_demo_hello_proto_rawDescGZIP(), []int{2}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_demo_hello_proto protoreflect.FileDescriptor

const file_demo_hello_proto_rawDesc = "" +
	"\n" +
	"\x10demo/hello.proto\x12\x05hello\"\xc3\x01\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x12\x15\n" +
	"\x06is_vip\x18\x03 \x01(\bR\x05isVip\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\"\n" +
	"\x05level\x18\x05 \x01(\x0e2\f.hello.LevelR\x05level\x12(\n" +
	"\aaddress\x18\x06 \x01(\v2\x0e.hello.AddressR\aaddress\x12\x14\n" +
	"\x05count\x18\a \x01(\x05R\x05count\"5\n" +
	"\aAddress\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x16\n" +
	"\x06street\x18\x02 \x01(\tR\x06street\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*B\n" +
	"\x05Level\x12\x15\n" +
	"\x11LEVEL_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vLEVEL_BASIC\x10\x01\x12\x11\n" +
	"\rLEVEL_PREMIUM\x10\x022\xf7\x01\n" +
	"\aGreeter\x122\n" +
	"\bSayHello\x12\x13.hello.HelloRequest\x1a\x11.hello.HelloReply\x12:\n" +
	"\x0eSayHelloStream\x12\x13.hello.HelloRequest\x1a\x11.hello.HelloReply0\x01\x12@\n" +
	"\x14SayHelloClientStream\x12\x13.hello.HelloRequest\x1a\x11.hello.HelloReply(\x01\x12:\n" +
	"\fSayHelloBidi\x12\x13.hello.HelloRequest\x1a\x11.hello.HelloReply(\x010\x01B\x17Z\x15LearnGo/api/demo;demob\x06proto3"

var (
	file_demo_hello_proto_rawDescOnce sync.Once
	file_demo_hello_proto_rawDescData []byte
)

func file_demo_hello_proto_rawDescGZIP() []byte {
	file_demo_hello_proto_rawDescOnce.Do(func() {
		file_demo_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_demo_hello_proto_rawDesc), len(file_demo_hello_proto_rawDesc)))
	})
	return file_demo_hello_proto_rawDescData
}

var file_demo_hello_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_demo_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_demo_hello_proto_goTypes = []any{
	(Level)(0),           // 0: hello.Level
	(*HelloRequest)(nil), // 1: hello.HelloRequest
	(*Address)(nil),      // 2: hello.Address
	(*HelloReply)(nil),   // 3: hello.HelloReply
}
var file_demo_hello_proto_depIdxs = []int32{
	0, // 0: hello.HelloRequest.level:type_name -> hello.Level
	2, // 1: hello.HelloRequest.address:type_name -> hello.Address
	1, // 2: hello.Greeter.SayHello:input_type -> hello.HelloRequest
	1, // 3: hello.Greeter.SayHelloStream:input_type -> hello.HelloRequest
	1, // 4: hello.Greeter.SayHelloClientStream:input_type -> hello.HelloRequest
	1, // 5: hello.Greeter.SayHelloBidi:input_type -> hello.HelloRequest
	3, // 6: hello.Greeter.SayHello:output_type -> hello.HelloReply
	3, // 7: hello.Greeter.SayHelloStream:output_type -> hello.HelloReply
	3, // 8: hello.Greeter.SayHelloClientStream:output_type -> hello.HelloReply
	3, // 9: hello.Greeter.SayHelloBidi:output_type -> hello.HelloReply
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_demo_hello_proto_init() }
func file_demo_hello_proto_init() {
	if File_demo_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_demo_hello_proto_rawDesc), len(file_demo_hello_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demo_hello_proto_goTypes,
		DependencyIndexes: file_demo_hello_proto_depIdxs,
		EnumInfos:         file_demo_hello_proto_enumTypes,
		MessageInfos:      file_demo_hello_proto_msgTypes,
	}.Build()
	File_demo_hello_proto = out.File
	file_demo_hello_proto_goTypes = nil
	file_demo_hello_proto_depIdxs = nil
}
